name: Pycodestyle Check

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9  # Wybierz odpowiednią wersję Pythona

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle

    - name: Run Pycodestyle
      run: |
        pycodestyle .

